[book]
title = "Tech Notes"
authors = ["x5zone"]
language = "zh"
src = "."

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = ["mdbook/custom.css", "mdbook/katex.min.css"]
additional-js = ["mdbook/katex.min.js", "mdbook/katex-auto-render.min.js", "mdbook/katex-config.js", "mdbook/comments.js"]
git-repository-url = "https://github.com/x5zone/tech-notes"
edit-url-template = "https://github.com/x5zone/tech-notes/edit/main/{path}"

[output.html.fold]
enable = true
level = 0
